INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (1,'Sammy',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (2,'SANYO',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (3,'ウシオ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (4,'パチンコ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (5,'海物語',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (6,'ギャンブル',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (7,'万枚',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (8,'パチスロ 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (9,'新装開店',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (10,'パチンコ 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (11,'リニューアルオープン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (12,'パチスロ 設定',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (13,'パチンコ 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (14,'パチスロ 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (15,'目押し',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (16,'パチンコ 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (17,'サミー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (18,'パチンコ 歴史',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (19,'パチンコ 設定',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (20,'ういち',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (21,'パチスロ 設定判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (22,'ヒラヤマン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (23,'パチスロ 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (24,'SANKYO',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (25,'サミー アプリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (26,'サミー ゲーム',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (27,'押忍番長',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (28,'全6',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (29,'北電子',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (30,'スロット 目押し',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (31,'スロット 設定',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (32,'オフミー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (33,'P-martTV',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (34,'いそまる',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (35,'スロパチステーション',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (36,'チェリ男',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (37,'フェアリン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (38,'七瀬静香',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (39,'射駒タケシ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (40,'木村魚拓',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (41,'松本バッチ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (42,'梅屋シン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (43,'設定1',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (44,'設定6',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (45,'閉店くん',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (46,'髭原人',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (47,'みんジャグ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (48,'ミラクルジャグラー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (49,'スロット 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (50,'パチスロ 目押し',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (51,'パチンコ セグ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (52,'グランドオープン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (53,'スロット 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (54,'新台入替',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (55,'アイムジャグラー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (56,'ファンキージャグラー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (57,'マイジャグラー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (58,'ジャンバリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (59,'ヤルヲ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (60,'閉店ちゃん',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (61,'しのけん',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (62,'アニマルかつみ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (63,'ガル僧',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (64,'中武一日二膳',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (65,'政重ゆうき',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (66,'森本レオ子',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (67,'青山りょう',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (68,'ニューギン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (69,'大都技研',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (70,'ぱちガブッ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (71,'しおねえ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (72,'中段ちぇりこ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (73,'寺井一択',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (74,'全六',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (75,'緑ドン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (76,'ユニバ 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (77,'ユニバ ゲーム',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (78,'ゆう坊',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (79,'天草ヤスヲ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (80,'スロット 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (81,'カブトムシゆかり',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (82,'ユニバ アプリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (83,'設定判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (84,'ポコ美',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (85,'沖ヒカル',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (86,'諸積ゲンズブール',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (87,'スロット 判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (88,'スロパチ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (89,'ユニバーサル スロット',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (90,'みんなのジャグラー',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (91,'大崎一万発',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (92,'パチスロ 判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (93,'ジャグ連',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (94,'パチンコ 判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (95,'ユニバ 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (96,'青ドン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (97,'ユニバーサル 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (98,'パチスロ ビタ押し',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (99,'パチスロ 歴史',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (100,'YAMASA',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (101,'パチンカス',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (102,'スロット 設定判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (103,'倖田柚希',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (104,'大都技研 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (105,'攻略ライター',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (106,'ルーキー酒井',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (107,'サミー 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (108,'スロット ビタ押し',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (109,'純増',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (110,'サミー 機種',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (111,'ニューギン 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (112,'SANKYO 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (113,'北電子 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (114,'SANYO 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (115,'YAMASA 新台',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (116,'ぱちガブ アプリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (117,'ぱちガブッ アプリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (118,'サミネ アプリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (119,'ART当選',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (120,'ART抽選',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (121,'Sammy アプリ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (122,'Sammy ゲーム',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (123,'Sammy 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (124,'Sammy 機種',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (125,'Sammy 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (126,'Sammy 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (127,'ぱちガブ ゲーム',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (128,'ぱちガブ 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (129,'ぱちガブ 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (130,'ぱちガブッ ゲーム',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (131,'ぱちガブッ 攻略',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (132,'ぱちガブッ 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (133,'サミネ ゲーム',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (134,'セグ判別',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (135,'一確',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (136,'ぱちガブ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (137,'サミネ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (138,'YAMASA 機種',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (139,'YAMASA 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (140,'YAMASA 解析',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (141,'ビタ押し',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (142,'MYME',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (143,'工藤らぎ',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (144,'BIG確率',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (145,'REG確率',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (146,'ボーナス確率',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (147,'小役確率',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (148,'ユニバ 機種',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (149,'ユニバ 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (150,'ボーナス当選',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (151,'ボーナス抽選',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (152,'全台系',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (153,'大都技研 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (154,'プロライターチップス',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (155,'ライターチップス',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (156,'SANKYO 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (157,'SANYO 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (158,'VIVAドン',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (159,'ニューギン 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (160,'北電子 歴代',1,NOW(),'init',NOW(),'init',1);
INSERT INTO `campaign_keyword` (`keyword_id`,`keyword_name`,`version_no`,`created_at`,`created_by`,`updated_at`,`updated_by`,`is_actived`) VALUES (161,'ペロリナ',1,NOW(),'init',NOW(),'init',1);